name: Cypress tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'

    - name: Install project dependencies
      run: npm ci

    - name: Install Cypress globally
      run: npm install -g cypress

    - name: Fix node_modules permissions
      run: chmod -R 755 ./node_modules

    - name: Run Cypress tests on electron
      run: npx cypress run --config-file=cypress.config.js --record true --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser electron
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
